#!/bin/bash
#cactvsHOME="/lustre/beagle2/lpBuild/CANDLE/SAVI/savi_trial_run/apps/cactvs3.4.6.3"
cactvsHOME=$1
shift 1
TK_LIBRARY="$cactvsHOME/tk8.6/"
TCL_LIBRARY="$cactvsHOME/tcl8.6/"
TCLX_LIBRARY="$cactvsHOME/tclx8.4/"
BLT_LIBRARY="$cactvsHOME/blt3.0/"
TIX_LIBRARY="$cactvsHOME/tix8.4/"
#OS="Linux3.0" #Isn't really necessary
DATADIR="$cactvsHOME"
PATH="$cactvsHOME/lib/:$DATADIR:$PATH"
LD_LIBRARY_PATH="$cactvsHOME/lib:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH PATH
export TK_LIBRARY TCL_LIBRARY TCLX_LIBRARY BLT_LIBRARY TIX_LIBRARY OS DATADIR
PGM="$cactvsHOME/lib/tclcactvs"
ls -la $PGM
#echo LD: $LD_LIBRARY_PATH 
#echo PATH: $PATH 
#echo "$@"  
#echo $TK_LIBRARY $TCL_LIBRARY $TCLX_LIBRARY $BLT_LIBRARY $TIX_LIBRARY $OS $DATADIR 
exec "$PGM" -bd "$@"
