#!/bin/bash
# This script prepares the environment for tclcactvs and executes it 
# NOTE: Nothing in it should be dependent upon the machine it is run on (as long as it is UNIX/LINUX and runs bash)
cactvsHOME=$1
shift 1
TK_LIBRARY="$cactvsHOME/tk8.6/"
TCL_LIBRARY="$cactvsHOME/tcl8.6/"
TCLX_LIBRARY="$cactvsHOME/tclx8.4/"
BLT_LIBRARY="$cactvsHOME/blt3.0/"
TIX_LIBRARY="$cactvsHOME/tix8.4/"
#OS="Linux3.0" #Isn't really necessary
DATADIR="$cactvsHOME"
PATH="$cactvsHOME/lib/:$DATADIR:$PATH"
LD_LIBRARY_PATH="$cactvsHOME/lib:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH PATH
#The following doesn't seem to work or at least not work as I thought it would - LLP ANL July 2017
export TK_LIBRARY TCL_LIBRARY TCLX_LIBRARY BLT_LIBRARY TIX_LIBRARY OS DATADIR
PGM="$cactvsHOME/lib/tclcactvs"
ls -la $PGM
exec "$PGM" -bd "$@"
